services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=otlp-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./infra/prometheus.yaml:/etc/prometheus.yaml
      - /etc/localtime:/etc/localtime:ro
      - ./data/prometheus-data:/prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - '8081:16686' # Jaeger UI
      - '14268'
      - '14250'
    restart: unless-stopped

  opentelemetry-collector:
    hostname: opentelemetry-collector
    image: otel/opentelemetry-collector-contrib:0.108.0
    command:
      [
        '--config=/etc/otel-collector-config.yml',
        '--feature-gates=pkg.translator.prometheus.NormalizeName',
      ]
    volumes:
      - ./infra/otel-collector-config.yml:/etc/otel-collector-config.yml
    restart: unless-stopped
    environment:
      - DEPLOY_ENV=dev
    ports:
      - '8888:8888' # Prometheus metrics exposed by the collector
      - '8889:8889' # Prometheus exporter metrics
      - '4317:4317' # OTLP gRPC receiver

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - '3100:3100'
    command:
      - --config.file=/etc/loki/config/config.yaml
    volumes:
      - ./infra/loki-config.yaml:/etc/loki/config/config.yaml
      - ./loki-data:/loki
      - ./loki-wal:/wal

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./infra/grafana/provisioning:/etc/grafana/provisioning #https://grafana.com/docs/grafana/latest/administration/provisioning/
      - ./data/grafana-data:/var/lib/grafana
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '3032:3000'
    restart: unless-stopped
    depends_on:
      - prometheus
      - jaeger
      - opentelemetry-collector
    links:
      - opentelemetry-collector
      - prometheus
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_INSTALL_PLUGINS=https://storage.googleapis.com/integration-artifacts/grafana-exploretraces-app/grafana-exploretraces-app-latest.zip;grafana-traces-app

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tccdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: unless-stopped

networks:
  default:
    name: mynet

volumes:
  prometheus_data:
  loki:
  grafana_data:
  postgres_data:
