services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mynet
  api-gateway:
    build:
      context: ./api-gateway
    image: api-gateway:latest
    container_name: api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    networks:
      - mynet
  ms-auth:
    build:
      context: ./ms-auth
    image: ms-auth:latest
    container_name: ms-auth
    ports:
      - "3001:3001"
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_URL=http://prometheus:9090
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
