global:
  scrape_interval: 5s
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: api-gateway
    static_configs:
      # - targets: [192.168.0.10:3000]
      - targets: [api-gateway:3000]
  - job_name: ms-auth
    static_configs:
      # - targets: [192.168.0.10:3001]
      - targets: [ms-auth:9101]
