receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  attributes:
    actions:
      - action: insert
        key: env
        value: '${DEPLOY_ENV}'

exporters:
  # Exportador para Prometheus (métricas)
  prometheus:
    endpoint: 0.0.0.0:8889
    send_timestamps: true

  # Exportador OTLP para Jaeger (traces)
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true

  # Exportador para Loki (logs)
  loki:
    endpoint: 'http://loki:3100/loki/api/v1/push'

  debug:
    verbosity: detailed

extensions:
  zpages:
    endpoint: 0.0.0.0:55679

service:
  extensions: [zpages]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch, attributes]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki]
