{
 "title": "Loki Dashboard",
 "description": "Loki dashboard with quick search and timeline.",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   },
   {
    "name": "workload",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\"}, workload)"
   },
   {
    "name": "pod",
    "query": "label_values(mixin_pod_workload{namespace=\"$namespace\", workload=\"$workload\"}, pod)"
   },
   { "name": "search" }
  ]
 },
 "panels": [
  {
   "title": "Timeline Count of all log records",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({job!=\"\"} |~ \"$search\"[$__interval]))"
    }
   ]
  },
  {
   "title": "Logs - Api Gateway",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"api-gateway\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Logs - Order",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"ms-order\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Logs - Catalog",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"ms-catalog\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Logs - Notification",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"ms-notification\"} |~ \"$search\""
    }
   ]
  },
  {
   "title": "Logs - Auth",
   "type": "logs",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 103 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"ms-auth\"} |~ \"$search\""
    }
   ]
  }
 ]
}